### ISSUE TITLE
Поддержка css-модулей в storybook

### ISSUE THREAD

**Issue by Pistch** [yandex-shri-minsk-2018/deo-iuvante#20]

**Comment by NeXidan** [comment]
Добавить file-loader для в конфиг вебпака для сторибук
- из текущего массива `module.rules` сделать один с `{oneOf: ...}`
- добавить в конец `file-loader` как [тут](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L226) с добавлением .ejs в excludes

**Comment by Pistch** [comment]
Сделано
